apiVersion: apps/v1
kind: Deployment
metadata:
  name: harish
spec:
  replicas: 3
  selector:
    matchLabels:
      app: harish
  template:
    metadata:
      labels:
        app: harish
    spec:
      containers:
        - name: harish-container
          image: nginx:latest

